// Problem1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "iostream"
#include <windows.h>

int _tmain(int argc, _TCHAR* argv[])
{
    LARGE_INTEGER lTime1;
    LARGE_INTEGER lTime2;
    long diffTicks;
    
    std::cout << "Each new term in the Fibonacci sequence is generated by adding the previous two terms. \n"
        << "By starting with 1 and 2, the first 10 terms will be:\n"
        << "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
        << "Find the sum of all the even-valued terms in the sequence which do not exceed four million.\n\n";
    std::cout << "-Standard--------------------------------\n";

    QueryPerformanceCounter(&lTime1);
    
    int sum = 0;
    int prev1 = 0;
    int prev2 = 1;
    for (int i=2; i<=4000000; i+=prev1)
    {
        if (i%2 == 0)
            sum += i;
        prev1 = prev2;
        prev2 = i;
    }

    std::cout << "Sum = " <<  sum << "\n";

    //function
    QueryPerformanceCounter(&lTime2);
    diffTicks=lTime2.QuadPart-lTime1.QuadPart;  // ticks passed

    std::cout << "Execution Time : " << diffTicks << " ticks.\n";
/*
    std::cout << "-Fast------------------------------------\n";

    QueryPerformanceCounter(&lTime1);
    
    sum = 0;
    int i=3; int j=5;
    for (; (i<1000) || (j<1000);i+=3 )
    {
        sum+=i;
        if ((j<1000) && (j%3!=0))
            sum += j;
        j+=5;
    }

    std::cout << "Sum = " <<  sum << "\n";

    //function
    QueryPerformanceCounter(&lTime2);
    diffTicks=lTime2.QuadPart-lTime1.QuadPart;  // ticks passed

    std::cout << "Execution Time : " << diffTicks << " ticks.\n";
*/
    getchar();
	return 0;
}

